import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.container}>
  <h2 className={styles.title}>
    <span className={styles.titleWordA}>I </span>
    <span className={styles.titleWordB}>love </span>
    <span className={styles.titleWordC}>you </span>
    <span className={styles.titleWordD}>Gracie </span>
    <span className={styles.titleWordE}>;P</span>
  </h2>
</div>
      </main>
    </>
  )
}
